# This is a basic workflow to help you get started with Actions

name: Upgrade Libraries

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
defaults:
  run:
    shell: bash -leo pipefail {0}
env:
  HOME: /root
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: vamship/ci-nodejs

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Initialize nvm for project
        run: |
          pwd
          echo "------------"
          echo ${GITHUB_WORKSPACE}
          echo "------------"
          env
          echo "------------"
          cp /root/.nvmrc /
          nvm use
          
      - name: Update npm packages
        run: |
          pwd
          ncu -u

      - name: Commit changes made because of the updates
        run: |
          git config --global user.name 'Github Build'
          git config --global user.email 'vamship@users.noreply.github.com'
          git commit -am "Upgrade dependencies" || echo "Nothing to commit"
          git push

      - name: Update npm packages
        run: |
          pwd
          ncu -u
