# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
defaults:
  run:
    shell: bash
    working-directory: /root
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: vamship/ci-nodejs

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Dump nvm version
        run: |
          pwd
          cp /root/.nvmrc /
          echo ${HOME}
          export NVM_DIR="/root/.nvm"
          echo "Sourcing nvm.sh"
          . "/root/.nvm/nvm.sh" || echo "ERR: $?"
          echo "Printing current node version"
          nvm current || echo "ERR: $?"
          echo "Switching to default nvm version"
          nvm use lts/fermium || echo "ERR: $?"
          echo "Listing nvm versions"
          nvm ls || echo "ERR: $?"
          echo "Switching to nvmrc version"
          nvm use || echo "ERR: $?"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
